### ISSUE TITLE
Using your solution on my training data

### ISSUE THREAD

**Issue by amardeepjaiman** [mnboos/osm-instance-segmentation#2]
@mnboos ,

I am also trying to solve the similar problem. Where I have many high resolution aerial imagery captured from aircraft and corresponding vector data and I want to generate the Geo masks like you have generated in your solution for Bing map data. Since your tol airtiler work for Bing map and OSM data, can you suggest how to create training dataset using my own imagery and vector data? I also want to feed this Dataset to Mask RCNN network for instance segmentation.

My overall goal to find the difference between 2 images of the same location if any building size has been increased or new building is created or removed like this. Since you have worked on similar solution you would be a great help .

Thanks in advance,
Amardeep

**Comment by mnboos** [comment]
Hi @amardeepjaiman 

I think one approach would be to adapt the airtiler tool.

What kind of imagery data do you have? It would be convinient, if its already tiled.
